---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# marteloscope5

L'application marteloscope5 aide à la mise en place et au traitement de données issues de marteloscopes. 
<!-- badges: start -->
<!-- badges: end -->



## Installation

You can install the development version of marteloscope5 like so:

``` r
# FILL THIS IN! HOW CAN PEOPLE INSTALL YOUR DEV PACKAGE?
```

## Usage

L’application est destinée aux techniciens forestiers et aux animateurs sylvicoles souhaitant mettre en place une activité de Marteloscope.
A partir d'un fichier contenant la localisation, l'essence et le diamètres des arbres ; le module 'Qfield' produit un fichier .gpkg modifiable sur téléphone via l'application Qfield qui permettra d'effectuer un martelage. 
Une fois le martelage effectué l'application via l'onglet Résultat va permettre d'analyser et de comparer les résultats des différents martelages effectués. il suffira de charger les fichiers .gpkg sur l'application.

## Support

L'onglet Ressources fourni des informations sur commment choisir un arbre à marteler; et comment utiliser l'application (fichier Notice Application)

delacroix.emile@gmail.com
